before_script:
    - date
    - uname -a
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - printenv | sort
    

python:
    image: python:3
    script:
    - python3 main.py
