# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.5

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:9.5

variables:
  POSTGRES_DB: booksdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
    - date
    - uname -a
    - pip install -r requirements.txt
    - printenv | sort

connect:
    image: postgres
    script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"